### ISSUE TITLE
overall text edits and updates

### ISSUE THREAD

**Issue by sherrirose** [StanfordHPDS/lab_manual#21]
Including:
- ~~Grant numbers & guidance for acknowledging funding in papers~~ 
- Stress documentation-based Lab, formalism.
- ~~Remove data experts~~ 
- ~~More clarity around GitHub repositories~~
- Link onboading internal document

**Comment by malcolmbarrett** [comment]
> More clarity around GitHub repositories

This might be addressed in #15

**Comment by sherrirose** [comment]
> Remove data experts

Addressed & merged
